"""
Django settings for classes project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
# settings.py

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3tj#b*u^@yxuez@nw036s5zk%8t^%_l+2=*&n3!7(d1ek14$7k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False # Correctly set to False

ALLOWED_HOSTS = [
    'personal-portfolio-tanvi-0ce4.onrender.com', # Your Render service URL
    'www.yourdomain.com', # If you have a custom domain
    'localhost',
    '127.0.0.1',
] # This looks correct for Render

INSTALLED_APPS = [
    # ... other apps
    'django.contrib.staticfiles', # Make sure this is included
    'resume' # Your app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # IMPORTANT: Add WhiteNoise middleware here, right after SecurityMiddleware
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'classes.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"], # Ensure your templates dir is correctly referenced
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'classes.wsgi.application' # Correctly set

# ... database settings ...

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# This is for development. Collectstatic will gather files from here and other apps' static dirs.
STATICFILES_DIRS = [
    BASE_DIR / 'static',
    # If your static files are in your app's static folder (e.g., resume/static/),
    # you don't strictly need to list it here, as Django finds them automatically.
    # But it's good practice to have a project-level static folder if you use one.
]

# This is the directory where collectstatic will put all your static files for production.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Use WhiteNoise to serve static files efficiently in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redundant STATICFILES_DIRS entry - remove one of them
# STATICFILES_DIRS=[
#   os.path.join(BASE_DIR, 'static')
# ]
